version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "nest-lambda-app-prod-v1"
resolve_s3 = true
s3_prefix = "nest-lambda-app"
region = "us-east-1"
confirm_changeset = true  # 生产环境需要确认
capabilities = "CAPABILITY_IAM"
disable_rollback = false
image_repositories = []
parameter_overrides = [
    "Environment=$ENVIRONMENT",
    "DatabaseUrlWrite=$DATABASE_URL_WRITE",
    "DatabaseUrlRead=$DATABASE_URL_READ"
]
# 生产环境额外的安全和监控标签
tags = [
    "Environment=\"production\"",
    "Project=\"nest-lambda-app-prod-v1\"",
    "CostCenter=\"engineering\"",
    "Owner=\"backend-team\""
]